NumPy

In [37]:
import numpy as np
import numpy.random as rand
import pandas as pd

1. Create a 1D array from a list.


In [38]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

2. Create a 3x3 array of zeros.


In [39]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Create a 2x2 array of ones.

In [6]:
arr=np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

4. Generate array from 0 to 10 (exclusive).

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5. Create 5 evenly spaced numbers between 0 and 1.


In [9]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. Create a 4x4 identity matrix.

In [11]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. Reshape 1D array to 2D.

In [22]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.reshape(1,5))

[1 2 3 4 5]
[[1 2 3 4 5]]


8. Get the shape and dtype of an array.

In [40]:
arr=rand.randint(10,50,(1,2))
print(arr)
print(arr.shape)
print(arr.dtype)

[[46 36]]
(1, 2)
int32


9. Reverse a NumPy array.

In [41]:
arr=rand.randint(1,10,(5,))
print(f'Original Array: {arr}')
print(f'Reversed Array: {arr[::-1]}')
arr

Original Array: [5 1 9 1 4]
Reversed Array: [4 1 9 1 5]


array([5, 1, 9, 1, 4], dtype=int32)

10. Extract even numbers from an array.

In [42]:
arr=rand.randint(1,10,(5,))
print(arr)
print(arr[arr%2==0]) # Boolean indexing is used

[4 9 2 9 9]
[4 2]


11. Find the max in each row.

In [43]:
arr=rand.randint(10,50,(3,4))
print(arr)
print('Maximum number in each row are:')
for i in arr:
    print(i.max())

[[17 38 37 36]
 [35 30 44 48]
 [45 35 33 30]]
Maximum number in each row are:
38
48
45


12. Compute the mean, std, and median of an array.


In [44]:
arr=rand.randint(10,50,(3,4))
print(arr)
print(f'Mean: {arr.mean()}')
print(f'Standard Deviation: {arr.std()}')
print(f'Median: {np.median(arr.flatten())}')

[[45 41 37 35]
 [45 29 18 27]
 [38 23 40 17]]
Mean: 32.916666666666664
Standard Deviation: 9.482073730056218
Median: 36.0


13. Stack two arrays vertically.

In [45]:
arr1=rand.randint(1,5,(2,3))
arr2=rand.randint(10,50,(2,3))
print(f'Array 1:\n{arr1}')
print(f'Array 2:\n{arr2}')
print(f'Array 1 and 2 vertically stacked:\n{np.concatenate((arr1,arr2),axis=0)}')

Array 1:
[[3 1 4]
 [4 2 1]]
Array 2:
[[25 45 21]
 [43 28 17]]
Array 1 and 2 vertically stacked:
[[ 3  1  4]
 [ 4  2  1]
 [25 45 21]
 [43 28 17]]


14. Stack two arrays horizontally.

In [46]:
arr1=rand.randint(1,5,(2,3))
arr2=rand.randint(10,50,(2,3))
print(f'Array 1:\n{arr1}')
print(f'Array 2:\n{arr2}')
print(f'Array 1 and 2 vertically stacked:\n{np.concatenate((arr1,arr2),axis=1)}')

Array 1:
[[3 2 2]
 [2 3 2]]
Array 2:
[[34 18 33]
 [47 31 39]]
Array 1 and 2 vertically stacked:
[[ 3  2  2 34 18 33]
 [ 2  3  2 47 31 39]]


15. Stack two arrays horizontally.


In [47]:
arr1=rand.randint(1,5,(3,4))
arr2=rand.randint(10,50,(3,4))
print(f'Array 1:\n{arr1}')
print(f'Array 2:\n{arr2}')
print(f'Array 1 and 2 vertically stacked:\n{np.concatenate((arr1,arr2),axis=1)}')

Array 1:
[[3 1 2 3]
 [3 3 2 1]
 [1 3 3 3]]
Array 2:
[[16 41 36 46]
 [40 11 22 11]
 [40 38 29 19]]
Array 1 and 2 vertically stacked:
[[ 3  1  2  3 16 41 36 46]
 [ 3  3  2  1 40 11 22 11]
 [ 1  3  3  3 40 38 29 19]]


16. Find the unique values and their counts.


In [49]:
arr=rand.randint(1,10,(5,))
print(arr)
unique, counts=np.unique(arr,return_counts=True)
print(f'Unique values in array: {unique}')
print(f'Respective counts of the unique numbers: {counts}')

[5 1 6 6 2]
Unique values in array: [1 2 5 6]
Respective counts of the unique numbers: [1 1 1 2]


17. Replace NaN with column means.


In [50]:
arr=np.array([
    [1.0, 2.0, np.nan],
    [4.0, np.nan, 6.0],
    [7.0, 8.0, 9.0]
])
print(arr)
col_means=np.nanmean(arr,axis=0)

nan_indices=np.where(np.isnan(arr))

arr[nan_indices]=np.take(col_means,nan_indices[1])
print(arr)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


18. Get index of min and max values.


In [51]:
arr=rand.randint(1,10,(5,))
print(f'Array: {arr}')
print(f'Minimum value in array: {arr.min()}')
print(f'Maximum value in array: {arr.max()}')
print(f'Index of Minimum value in array: {np.where(arr==arr.min())[0]}')
print(f'Index of Maximum value in array: {np.where(arr==arr.max())[0]}')

Array: [8 8 2 5 4]
Minimum value in array: 2
Maximum value in array: 8
Index of Minimum value in array: [2]
Index of Maximum value in array: [0 1]


19. Create a 3D array of random integers.



In [52]:
arr_3d=rand.randint(10,90,(1,2,3))
arr_3d

array([[[54, 61, 64],
        [20, 45, 53]]], dtype=int32)

20. Use np.where() to replace values


In [90]:
arr = np.array([34, 67, 12, 89, 45])
new_arr = np.where(arr > 50, 'Greater than 50', arr)

print("Original:", arr)
print("Modified:", new_arr)

Original: [34 67 12 89 45]
Modified: ['34' 'Greater than 50' '12' 'Greater than 50' '45']


Pandas

1. Create a Series using a Python list.


In [ ]:
ser=pd.Series(rand.randint(10,70,(5,)))
ser

0    13
1    52
2    32
3    34
4    51
dtype: int32

2. Create a Series with custom string indices.




In [55]:
ser=pd.Series(['Leonardo DiCaprio','Hollywood','1974','Titanic, The Wolf of Wall Street'],index=['Name','Actor Domain','Born Year','Some Famous Movies'])
ser

Name                                 Leonardo DiCaprio
Actor Domain                                 Hollywood
Born Year                                         1974
Some Famous Movies    Titanic, The Wolf of Wall Street
dtype: object

3. Create a Series from a dictionary.


In [58]:
ser=pd.Series({
    'Math':rand.randint(1,100),
    'Science':rand.randint(1,100),
    'English':rand.randint(1,100),
    'History':rand.randint(1,100),
    'Computer Science':rand.randint(1,100)
    })
ser

Math                72
Science             84
English             12
History             65
Computer Science    10
dtype: int64

4. Access first 3 elements of a Series.


In [62]:
ser=pd.Series(rand.randint(10,50,(5,)))
print(ser)
print('First 3 elements of the series: ')
print(ser[:3])

0    39
1    33
2    15
3    31
4    47
dtype: int32
First 3 elements of the series: 
0    39
1    33
2    15
dtype: int32


5. Filter Series elements greater than 50.



In [69]:
ser=pd.Series(rand.randint(10,100,(5,)))
print(ser)
print(f'Series elements greater than 50:\n{ser[ser>50]}') 

0    27
1    71
2    97
3    99
4    33
dtype: int32
Series elements greater than 50:
1    71
2    97
3    99
dtype: int32


6. Add two Series with different indices.



In [73]:
ser1=pd.Series(rand.randint(10,100,(5,)),index=[10,20,30,40,50])
ser2=pd.Series(rand.randint(10,100,(5,)),index=[1,2,3,4,5])
print(ser1)
print(ser2)
print(ser1.values+ser2.values)

10    32
20    14
30    72
40    39
50    50
dtype: int32
1    12
2    65
3    16
4    17
5    71
dtype: int32
[ 44  79  88  56 121]



7. Multiply a Series by a scalar.


In [74]:
ser=pd.Series(rand.randint(10,100,(5,)))
ser*5

0    100
1    180
2    320
3     60
4     50
dtype: int32

8. Use .multiply() method to multiply with scalar.


In [78]:
ser=pd.Series(rand.randint(10,100,(5,)))
print(ser)
ser.multiply(5)
ser.multiply(5)

0    21
1    18
2    48
3    33
4    64
dtype: int32


0    105
1     90
2    240
3    165
4    320
dtype: int32

10. Sort Series by values descending.


In [81]:
ser=pd.Series(rand.randint(10,100,(5,)))
print(ser)
ser.sort_values(ascending=False)

0    41
1    97
2    41
3    40
4    32
dtype: int32


1    97
0    41
2    41
3    40
4    32
dtype: int32

11. Sort Series by index.


In [84]:
ser=pd.Series({
    15:'5 x 3',
    25:'5 x 5',
    5:'5 x 1',
})
print(ser)
ser.sort_index()

15    5 x 3
25    5 x 5
5     5 x 1
dtype: object


5     5 x 1
15    5 x 3
25    5 x 5
dtype: object

12. Check for null values.



In [91]:
ser=pd.Series([1,2,3,np.nan,5])
ser.isnull()

0    False
1    False
2    False
3     True
4    False
dtype: bool

14. Concatenate two Series using concat().


In [94]:
ser1=pd.Series(rand.randint(10,100,(5,)))
ser2=pd.Series(rand.randint(10,100,(5,)))
pd.concat((ser1,ser2))

0    12
1    58
2    11
3    54
4    75
0    93
1    76
2    94
3    10
4    64
dtype: int32

15. Concatenate two Series using append().


In [97]:
ser1=pd.Series(rand.randint(10,100,(5,)))
ser2=pd.Series(rand.randint(10,100,(5,)))
try: 
    ser1.append(ser2)
except AttributeError:
    print(f'append() function is deprecated in pandas version: {pd.__version__}')

append() function is deprecated in pandas version: 2.2.3


16. Retrieve first 5 elements using .head()



In [104]:
ser=pd.Series(rand.randint(10,100,(15,)))
print(ser)
print()
print(f'First five values of the series:\n{ser.head()}')

0     54
1     41
2     47
3     12
4     87
5     71
6     87
7     96
8     75
9     16
10    80
11    48
12    22
13    27
14    83
dtype: int32

First five values of the series:
0    54
1    41
2    47
3    12
4    87
dtype: int32


17. Retrieve last 5 elements using .tail()


In [105]:
ser=pd.Series(rand.randint(10,100,(15,)))
print(ser)
print()
print(f'First five values of the series:\n{ser.tail()}')

0     11
1     97
2     87
3     11
4     23
5     15
6     94
7     38
8     50
9     62
10    32
11    94
12    70
13    12
14    30
dtype: int32

First five values of the series:
10    32
11    94
12    70
13    12
14    30
dtype: int32


18. Convert Series to DataFrame.


In [106]:
ser=pd.Series(rand.randint(10,100,(15,)))
ser.to_frame()

0
0   87
1   30
2   68
3   94
4   72
5   42
6   61
7   57
8   22
9   46
10  24
11  80
12  65
13  93
14  22

19. Replace NaN with 0.


In [110]:
df=pd.DataFrame([1,2,3,np.nan,4,5])
print(df)
print()
print(df.replace(np.nan,0))

     0
0  1.0
1  2.0
2  3.0
3  NaN
4  4.0
5  5.0

     0
0  1.0
1  2.0
2  3.0
3  0.0
4  4.0
5  5.0


20. Drop missing values.


In [111]:
df=pd.DataFrame([1,2,3,np.nan,4,5])
df.dropna()

0
0  1.0
1  2.0
2  3.0
4  4.0
5  5.0

21. Check Series data type.



In [112]:
ser=pd.Series([1,2,3,np.nan,4,5])
ser.dtype

dtype('float64')